// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_9l1sQCNxIazwXmV8GszMlW10nbw_KkE',
    appId: '1:949357791683:web:0ebc73533e379642735576',
    messagingSenderId: '949357791683',
    projectId: 'fire-feed-app-2ee1a',
    authDomain: 'fire-feed-app-2ee1a.firebaseapp.com',
    storageBucket: 'fire-feed-app-2ee1a.firebasestorage.app',
    measurementId: 'G-LCNDTHD0BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByNCiGElHmH3ficoPvzOl_ZhRNBRdbuBY',
    appId: '1:949357791683:android:1fd3ab6043e9d763735576',
    messagingSenderId: '949357791683',
    projectId: 'fire-feed-app-2ee1a',
    storageBucket: 'fire-feed-app-2ee1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR_YrW3AB_N9zPFIBG23wHJcM9byXXdm8',
    appId: '1:949357791683:ios:50dd9ba7eb5cfc9a735576',
    messagingSenderId: '949357791683',
    projectId: 'fire-feed-app-2ee1a',
    storageBucket: 'fire-feed-app-2ee1a.firebasestorage.app',
    iosBundleId: 'com.example.fireFeedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR_YrW3AB_N9zPFIBG23wHJcM9byXXdm8',
    appId: '1:949357791683:ios:50dd9ba7eb5cfc9a735576',
    messagingSenderId: '949357791683',
    projectId: 'fire-feed-app-2ee1a',
    storageBucket: 'fire-feed-app-2ee1a.firebasestorage.app',
    iosBundleId: 'com.example.fireFeedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_9l1sQCNxIazwXmV8GszMlW10nbw_KkE',
    appId: '1:949357791683:web:9706b122e973250a735576',
    messagingSenderId: '949357791683',
    projectId: 'fire-feed-app-2ee1a',
    authDomain: 'fire-feed-app-2ee1a.firebaseapp.com',
    storageBucket: 'fire-feed-app-2ee1a.firebasestorage.app',
    measurementId: 'G-1GVSXBN1HD',
  );
}
