// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzXKyRt26HeFE3-1Xv82MaLCn4z4WUJbs',
    appId: '1:934546357699:web:ed4ca3cf6f236a9ab49176',
    messagingSenderId: '934546357699',
    projectId: 'firefeed-6f020',
    authDomain: 'firefeed-6f020.firebaseapp.com',
    storageBucket: 'firefeed-6f020.firebasestorage.app',
    measurementId: 'G-L5CLVFDS0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjGmEtamTSTE0oXAsLIq9FpVicEm5uyOg',
    appId: '1:934546357699:android:c81bcd645b1b90afb49176',
    messagingSenderId: '934546357699',
    projectId: 'firefeed-6f020',
    storageBucket: 'firefeed-6f020.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4u-6MifzPF8SnIhLoZ6NE3bJhtGx33Sc',
    appId: '1:934546357699:ios:7ea149e0a98fe274b49176',
    messagingSenderId: '934546357699',
    projectId: 'firefeed-6f020',
    storageBucket: 'firefeed-6f020.firebasestorage.app',
    iosBundleId: 'com.example.fireFeedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4u-6MifzPF8SnIhLoZ6NE3bJhtGx33Sc',
    appId: '1:934546357699:ios:7ea149e0a98fe274b49176',
    messagingSenderId: '934546357699',
    projectId: 'firefeed-6f020',
    storageBucket: 'firefeed-6f020.firebasestorage.app',
    iosBundleId: 'com.example.fireFeedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzXKyRt26HeFE3-1Xv82MaLCn4z4WUJbs',
    appId: '1:934546357699:web:f84f4434f007eaa1b49176',
    messagingSenderId: '934546357699',
    projectId: 'firefeed-6f020',
    authDomain: 'firefeed-6f020.firebaseapp.com',
    storageBucket: 'firefeed-6f020.firebasestorage.app',
    measurementId: 'G-SMSHETG9FV',
  );

}